import { useState, useMemo } from 'react';
import type { CalculationResult, SystemConfiguration } from '../types';
import { AuditModal } from './AuditModal';
import { EnergyAnalyticsChart } from './EnergyAnalyticsChart';
import { MarketAnalysis } from './MarketAnalysis';
import { SaveReportModal } from './SaveReportModal';

import { estimateSystemCost } from '../utils/costEstimation';

interface ResultsSectionProps {
  standardResult: CalculationResult | null;
  marketResult?: CalculationResult | null;
  config?: SystemConfiguration;
  availableYears?: number[];
  selectedYear?: number;
  onSelectYear?: (year: number) => void;
  onSelectSimulation?: (annualProduction: number) => void;
  onBack?: () => void;
  onSaveReport?: (name: string) => void;
  existingReportNames?: string[];
}

function formatCurrency(value: number) {
  return new Intl.NumberFormat('en-IE', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(value);
}

function formatSignedCurrency(value: number) {
  const sign = value >= 0 ? '+' : '−';
  const abs = Math.abs(value);
  return `${sign}${formatCurrency(abs)}`;
}

function formatPercentFraction(fraction: number, digits = 1) {
  const f = Number.isFinite(fraction) ? fraction : 0;
  return `${(f * 100).toFixed(digits)}%`;
}

function formatNumber(value: number) {
  return new Intl.NumberFormat('en-IE', { maximumFractionDigits: 0 }).format(value);
}

export function ResultsSection({ 
  standardResult,
  marketResult,
  config, 
  availableYears = [], 
  selectedYear, 
  onSelectYear, 
  onSelectSimulation,
  onBack,
  onSaveReport,
  existingReportNames = []
}: ResultsSectionProps) {
  const [activeTab, setActiveTab] = useState<'standard' | 'market' | 'comparison'>('standard');
  const [auditOpen, setAuditOpen] = useState(false);
  const [saveModalOpen, setSaveModalOpen] = useState(false);

  const reportDate = new Date().toLocaleDateString();

  // Use the result based on active tab
  const activeResult = useMemo(() => {
    if (activeTab === 'market' && marketResult) return marketResult;
    return standardResult;
  }, [activeTab, standardResult, marketResult]);

  const analyticsYear = useMemo(() => {
    const y = activeResult?.audit?.year;
    if (typeof y === 'number') return y;
    const hk = activeResult?.audit?.hourly?.[0]?.hourKey;
    if (hk) {
      const maybeYear = Number(hk.slice(0, 4));
      if (Number.isFinite(maybeYear)) return maybeYear;
    }
    return new Date().getFullYear();
  }, [activeResult?.audit?.hourly, activeResult?.audit?.year]);

  const { solarYield, batteryYield } = useMemo(() => {
    if (!config || !activeResult) return { solarYield: 0, batteryYield: 0 };
    
    // Simple cost attribution logic
    // 1. Estimate standalone base costs
    const kwp = config.systemSizeKwp || (config.annualProductionKwh / 950); // Fallback estimation
    const kwh = config.batterySizeKwh || 0;
    
    const solarBaseCost = estimateSystemCost(kwp, 0);
    const batteryBaseCost = estimateSystemCost(0, kwh);
    
    // 2. Allocate Net Cost proportionally
    const totalBase = solarBaseCost + batteryBaseCost;
    if (totalBase <= 0) return { solarYield: 0, batteryYield: 0 };

    const solarShare = solarBaseCost / totalBase;
    const batteryShare = batteryBaseCost / totalBase;

    const solarAllocatedCost = activeResult.netCost * solarShare;
    const batteryAllocatedCost = activeResult.netCost * batteryShare;

    // 3. Calculate Yields (Annual Savings / Allocated Cost)
    // Note: Export revenue is attributed to Solar yield here as it's generated by solar
    const solarTotalSavings = activeResult.annualSolarToLoadSavings + activeResult.annualExportRevenue;
    
    const sYield = solarAllocatedCost > 0 ? solarTotalSavings / solarAllocatedCost : 0;
    const bYield = batteryAllocatedCost > 0 ? activeResult.annualBatteryToLoadSavings / batteryAllocatedCost : 0;

    return { solarYield: sYield, batteryYield: bYield };
  }, [config, activeResult]);

  const monthlyTotals = useMemo(() => {
    if (!activeResult?.audit?.monthly) return null;
    const monthly = activeResult.audit.monthly;
    return {
        payment: monthly.reduce((sum, m) => sum + (m.debtPayment ?? 0), 0),
        savings: monthly.reduce((sum, m) => sum + (m.savings ?? 0), 0),
        net: monthly.reduce((sum, m) => sum + (m.netOutOfPocket ?? ((m.savings ?? 0) - (m.debtPayment ?? 0))), 0),
        baseline: monthly.reduce((sum, m) => sum + (m.baselineCost ?? 0), 0),
        newBill: monthly.reduce((sum, m) => sum + (m.importCost ?? 0), 0)
    };
  }, [activeResult]);

  if (!standardResult) {
    return (
      <div className="bg-slate-50 rounded-xl border border-dashed border-slate-300 p-10 text-center h-full flex flex-col items-center justify-center text-slate-400">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-12 h-12 mb-4 opacity-50">
          <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
        </svg>
        <p>Run a calculation to generate the ROI report.</p>
      </div>
    );
  }

  return (
    <section className="bg-white rounded-2xl shadow-lg border border-slate-100 overflow-hidden">
      <div className="px-8 py-7 md:px-10 md:py-8 border-b border-slate-100">
        <div className="flex items-start justify-between gap-6">
          <div>
            <h2 className="text-3xl font-serif font-bold text-tines-dark leading-tight">Projected Impact Report</h2>
            <p className="mt-1 text-sm text-slate-500">Summary of costs, savings, and returns based on your inputs.</p>
          </div>
          <div className="flex items-center gap-4">
            {availableYears.length > 1 && onSelectYear && selectedYear && (
              <div className="flex items-center gap-2">
                <label htmlFor="year-select" className="text-sm font-medium text-slate-500">
                  Simulation Year:
                </label>
                <select
                  id="year-select"
                  value={selectedYear}
                  onChange={(e) => onSelectYear(Number(e.target.value))}
                  className="rounded-md border-slate-200 py-1 pl-3 pr-8 text-sm focus:border-indigo-500 focus:ring-indigo-500"
                >
                  {availableYears.map((y) => (
                    <option key={y} value={y}>
                      {y}
                    </option>
                  ))}
                </select>
              </div>
            )}
            <div className="text-sm font-medium text-slate-400 shrink-0">{reportDate}</div>
          </div>
        </div>
      </div>

      <div className="p-6 md:p-8">
        
        {/* Tab Navigation */}
        <div className="flex border-b border-slate-200 mb-8">
          <button
            onClick={() => setActiveTab('standard')}
            className={`px-6 py-3 text-sm font-medium border-b-2 transition-colors ${
              activeTab === 'standard'
                ? 'border-indigo-600 text-indigo-700'
                : 'border-transparent text-slate-500 hover:text-slate-700 hover:border-slate-300'
            }`}
          >
            Standard Analysis
          </button>
          {marketResult && (
            <button
              onClick={() => setActiveTab('market')}
              className={`px-6 py-3 text-sm font-medium border-b-2 transition-colors ${
                activeTab === 'market'
                  ? 'border-indigo-600 text-indigo-700'
                  : 'border-transparent text-slate-500 hover:text-slate-700 hover:border-slate-300'
              }`}
            >
              Market Rate Analysis
            </button>
          )}
          {marketResult && standardResult && (
            <button
              onClick={() => setActiveTab('comparison')}
              className={`px-6 py-3 text-sm font-medium border-b-2 transition-colors ${
                activeTab === 'comparison'
                  ? 'border-indigo-600 text-indigo-700'
                  : 'border-transparent text-slate-500 hover:text-slate-700 hover:border-slate-300'
              }`}
            >
              Comparison
            </button>
          )}
        </div>

        {/* --- STANDARD ANALYSIS TAB (combines overview + financials) --- */}
        {(activeTab === 'standard' || activeTab === 'market') && activeResult && (
          <div className="animate-in fade-in duration-300">
            {/* 1. Energy Analytics Chart (Top) */}
            {activeResult.audit?.hourly && activeResult.audit.hourly.length > 0 && (
              <div className="mb-8">
                <EnergyAnalyticsChart hourlyData={activeResult.audit.hourly} year={analyticsYear} />
              </div>
            )}

            {/* Savings Breakdown Compact Section */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
              <div className="bg-emerald-50 rounded-xl p-5 border border-emerald-100">
                 <div className="text-xs font-bold text-emerald-800 uppercase tracking-wider mb-1">Total Annual Savings</div>
                 <div className="text-2xl font-bold text-emerald-700">{formatCurrency(activeResult.annualSavings)}</div>
                 <div className="text-xs text-emerald-600/80 mt-1">Bill Reduction + Revenue</div>
              </div>
              
              <div className="bg-white rounded-xl p-5 border border-slate-100 shadow-sm">
                 <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">Solar Displacement</div>
                 <div className="text-xl font-bold text-slate-700">{formatCurrency(activeResult.annualSolarToLoadSavings)}</div>
                 <div className="text-xs text-slate-400 mt-1">Direct to Load</div>
                 {solarYield > 0 && (
                    <div className="mt-3 pt-3 border-t border-slate-50 flex justify-between items-center">
                      <span className="text-xs text-slate-400">Yield</span>
                      <span className="text-xs font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-full">
                        {formatPercentFraction(solarYield)}
                      </span>
                    </div>
                 )}
              </div>

              <div className="bg-white rounded-xl p-5 border border-slate-100 shadow-sm">
                 <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">Battery Displacement</div>
                 <div className="text-xl font-bold text-slate-700">{formatCurrency(activeResult.annualBatteryToLoadSavings)}</div>
                 <div className="text-xs text-slate-400 mt-1">Stored & Discharged</div>
                 {batteryYield > 0 && (
                    <div className="mt-3 pt-3 border-t border-slate-50 flex justify-between items-center">
                      <span className="text-xs text-slate-400">Yield</span>
                      <span className="text-xs font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-full">
                        {formatPercentFraction(batteryYield)}
                      </span>
                    </div>
                 )}
              </div>

              <div className="bg-white rounded-xl p-5 border border-slate-100 shadow-sm">
                 <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">Export Income</div>
                 <div className="text-xl font-bold text-slate-700">{formatCurrency(activeResult.annualExportRevenue)}</div>
                 <div className="text-xs text-slate-400 mt-1">Feed-in / Market</div>
              </div>
            </div>

            {/* Bill Comparison Card */}
            {monthlyTotals && (
              <div className="bg-slate-50 rounded-2xl p-8 border border-slate-200 mb-8">
                <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-6">Estimated Annual Electricity Bill</h3>
                <div className="flex flex-col md:flex-row items-center justify-between gap-8 md:gap-12">
                   <div className="text-center md:text-left">
                     <div className="text-sm font-medium text-slate-500 mb-1">Current Bill</div>
                     <div className="text-3xl md:text-4xl font-bold text-slate-700 tabular-nums">
                       {formatCurrency(monthlyTotals.baseline)}
                     </div>
                     <div className="text-xs text-slate-400 mt-2">Before Solar PV</div>
                   </div>
                   
                   <div className="flex-1 w-full md:w-auto relative h-12 flex items-center justify-center">
                      <div className="absolute inset-0 flex items-center">
                        <div className="w-full border-t-2 border-slate-200 md:border-dashed"></div>
                      </div>
                      <div className="relative bg-emerald-100 text-emerald-800 px-3 py-1 rounded-full text-sm font-bold border border-emerald-200 shadow-sm">
                        -{formatPercentFraction((monthlyTotals.baseline - monthlyTotals.newBill) / (monthlyTotals.baseline || 1), 0)}
                      </div>
                   </div>

                   <div className="text-center md:text-right">
                     <div className="text-sm font-medium text-slate-500 mb-1">Predicted Bill</div>
                     <div className="text-3xl md:text-4xl font-bold text-emerald-600 tabular-nums">
                       {formatCurrency(monthlyTotals.newBill)}
                     </div>
                     <div className="text-xs text-emerald-600/70 mt-2">After Solar PV</div>
                   </div>
                </div>
              </div>
            )}

            {/* Monthly Before/After Table */}
            {activeResult.audit?.monthly && activeResult.audit.monthly.length === 12 && (
              <div className="rounded-xl border border-slate-100 bg-white shadow-sm overflow-hidden mb-8">
                <div className="px-6 py-4 border-b border-slate-100 bg-slate-50/50">
                  <h3 className="text-sm font-bold tracking-wider text-slate-500 uppercase">Monthly Bill Comparison</h3>
                  <p className="text-xs text-slate-400 mt-1">Before and after solar PV installation</p>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm text-left">
                    <thead className="bg-slate-50 text-xs text-slate-500 uppercase font-semibold">
                      <tr>
                        <th className="px-6 py-3">Month</th>
                        <th className="px-6 py-3 text-right">Before</th>
                        <th className="px-6 py-3 text-right">After</th>
                        <th className="px-6 py-3 text-right">Savings</th>
                        <th className="px-6 py-3 text-right">Spill Rate</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {activeResult.audit.monthly.map((m) => {
                        const monthName = new Date(2000, m.monthIndex, 1).toLocaleString('en-IE', { month: 'short' });
                        const baseline = m.baselineCost ?? 0;
                        const importCost = m.importCost ?? 0;
                        const exportRevenue = m.exportRevenue ?? 0;
                        // Net bill = Import cost - Export revenue (can be negative for credits)
                        const netBill = importCost - exportRevenue;
                        // Savings = Baseline - Net bill (total financial benefit)
                        const savings = baseline - netBill;
                        const spillRate = m.generation > 0 ? m.gridExport / m.generation : 0;
                        const isHighSpill = spillRate > 0.3;
                        
                        return (
                          <tr key={m.monthIndex} className="hover:bg-slate-50/50 transition-colors">
                            <td className="px-6 py-3 font-medium text-slate-700">{monthName}</td>
                            <td className="px-6 py-3 text-right text-slate-600 tabular-nums">{formatCurrency(baseline)}</td>
                            <td className={`px-6 py-3 text-right tabular-nums font-medium ${
                              netBill < 0 ? 'text-emerald-700' : 'text-emerald-600'
                            }`}>
                              {formatCurrency(Math.max(0, netBill))}
                              {netBill < 0 && <span className="ml-1 text-xs">(€{Math.abs(netBill).toFixed(0)} credit)</span>}
                            </td>
                            <td className="px-6 py-3 text-right text-emerald-600 tabular-nums font-medium">
                              {formatCurrency(savings)}
                            </td>
                            <td className={`px-6 py-3 text-right tabular-nums font-medium ${
                              isHighSpill ? 'text-amber-600' : 'text-slate-600'
                            }`}>
                              {formatPercentFraction(spillRate)}
                              {isHighSpill && <span className="ml-1 text-xs">⚠️</span>}
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                    {monthlyTotals && (
                      <tfoot className="bg-slate-50 font-bold border-t border-slate-200">
                        <tr>
                          <td className="px-6 py-4 text-slate-800">Total</td>
                          <td className="px-6 py-4 text-right text-slate-700 tabular-nums">{formatCurrency(monthlyTotals.baseline)}</td>
                          <td className="px-6 py-4 text-right text-emerald-700 tabular-nums">{formatCurrency(monthlyTotals.newBill)}</td>
                          <td className="px-6 py-4 text-right text-emerald-700 tabular-nums">
                            {formatCurrency(monthlyTotals.baseline - monthlyTotals.newBill)}
                          </td>
                          <td className="px-6 py-4 text-right text-slate-700 tabular-nums">
                            {formatPercentFraction(activeResult.annualExport / (activeResult.annualGeneration || 1))}
                          </td>
                        </tr>
                      </tfoot>
                    )}
                  </table>
                </div>
              </div>
            )}

            {/* Solar Sizing Sensitivity Analysis */}
            {activeResult && activeResult.sensitivityAnalysis && (
              <div className="rounded-xl border border-slate-100 bg-white shadow-sm overflow-hidden mb-8">
                <div className="px-6 py-4 border-b border-slate-100 bg-slate-50/50 flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-bold tracking-wider text-slate-500 uppercase">Solar Sizing Sensitivity</h3>
                    <p className="text-xs text-slate-400 mt-0.5">
                      Year 1 vs Year 10 cumulative net cash flow. Click a row to simulate that system size.
                    </p>
                  </div>
                </div>
                
                <div className="overflow-x-auto">
                  <table className="w-full text-sm text-left">
                    <thead className="bg-slate-50 text-xs text-slate-500 uppercase font-semibold">
                      <tr>
                        <th className="px-6 py-3">PV Size (Annual kWh)</th>
                        <th className="px-6 py-3 text-right">No Battery <span className="block text-[10px] font-normal text-slate-400">Yr1 | Yr10 Net</span></th>
                        <th className="px-6 py-3 text-right">With Battery <span className="block text-[10px] font-normal text-slate-400">Yr1 | Yr10 Net</span></th>
                        <th className="px-6 py-3 text-right">Scale Factor</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {activeResult.sensitivityAnalysis.rows.map((row) => {
                        const isCurrent = Math.abs(row.scaleFactor - 1.0) < 0.01;
                        
                        const formatProfit = (val: number) => {
                           const isPos = val >= 0;
                           return (
                             <span className={isPos ? 'text-emerald-700 font-bold' : 'text-rose-600 font-medium'}>
                               {formatSignedCurrency(val)}
                             </span>
                           );
                        };

                        return (
                          <tr 
                            key={row.scaleFactor} 
                            onClick={() => !isCurrent && onSelectSimulation?.(row.annualGenerationKwh)}
                            className={`transition-colors ${
                              isCurrent 
                                ? 'bg-slate-50/80 cursor-default' 
                                : 'hover:bg-indigo-50 cursor-pointer group'
                            }`}
                          >
                            <td className="px-6 py-3">
                              <div className="font-medium text-slate-700 group-hover:text-indigo-700 tabular-nums">
                                {formatNumber(row.annualGenerationKwh)} kWh
                              </div>
                              {isCurrent && (
                                <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-indigo-100 text-indigo-800 mt-1">
                                  Current
                                </span>
                              )}
                            </td>
                            
                            <td className="px-6 py-3 text-right tabular-nums">
                               <div className="flex flex-col items-end gap-0.5">
                                 <div className="text-sm font-medium">{formatProfit(row.noBattery.year1NetCashFlow)}</div>
                                 <div className="text-xs">{formatProfit(row.noBattery.year10NetCashFlow)}</div>
                               </div>
                               <div className="text-[10px] text-slate-400 mt-1">
                                 Export: {(row.noBattery.exportPaidFraction * 100).toFixed(0)}% paid
                                 {row.noBattery.exportUnpaidFraction > 0.01 && (
                                   <span className="text-amber-600"> + {(row.noBattery.exportUnpaidFraction * 100).toFixed(0)}% unpaid</span>
                                 )}
                               </div>
                            </td>

                            <td className="px-6 py-3 text-right tabular-nums">
                               <div className="flex flex-col items-end gap-0.5">
                                 <div className="text-sm font-medium">{formatProfit(row.withBattery.year1NetCashFlow)}</div>
                                 <div className="text-xs">{formatProfit(row.withBattery.year10NetCashFlow)}</div>
                               </div>
                               <div className="text-[10px] text-slate-400 mt-1">
                                 {formatNumber(row.withBattery.batterySizeKwh)} kWh | Export: {(row.withBattery.exportPaidFraction * 100).toFixed(0)}%
                                 {row.withBattery.exportUnpaidFraction > 0.01 && (
                                   <span className="text-amber-600"> +{(row.withBattery.exportUnpaidFraction * 100).toFixed(0)}%</span>
                                 )}
                               </div>
                            </td>

                            <td className="px-6 py-3 text-right tabular-nums text-slate-500">
                              {row.scaleFactor}×
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
                <div className="px-6 py-3 bg-slate-50 border-t border-slate-100 text-xs text-slate-500">
                  {activeResult.sensitivityAnalysis.note}
                </div>
              </div>
            )}

            {/* Legacy Solar Spillage Sensitivity Analysis (Fallback) */}
            {activeResult && !activeResult.sensitivityAnalysis && activeResult.solarSpillageAnalysis && (
              <div className="rounded-xl border border-slate-100 bg-white shadow-sm overflow-hidden mb-8">
                <div className="px-6 py-4 border-b border-slate-100 bg-slate-50/50 flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-bold tracking-wider text-slate-500 uppercase">Solar Sizing Sensitivity</h3>
                    <p className="text-xs text-slate-400 mt-0.5">
                      Click a row to simulate that system size.
                    </p>
                  </div>
                </div>
                
                <div className="overflow-x-auto">
                  <table className="w-full text-sm text-left">
                    <thead className="bg-slate-50 text-xs text-slate-500 uppercase font-semibold">
                      <tr>
                        <th className="px-6 py-3">PV Size (Annual kWh)</th>
                        <th className="px-6 py-3 text-right">Scale Factor</th>
                        <th className="px-6 py-3 text-right">Exported</th>
                        <th className="px-6 py-3 text-right">Spillage %</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {activeResult.solarSpillageAnalysis.curve.map((p) => {
                        const isCurrent = Math.abs(p.scaleFactor - 1.0) < 0.01;
                        const isHighSpill = p.spillageFraction > 0.3;
                        
                        return (
                          <tr 
                            key={p.scaleFactor} 
                            onClick={() => !isCurrent && onSelectSimulation?.(p.annualGenerationKwh)}
                            className={`transition-colors ${
                              isCurrent 
                                ? 'bg-slate-50/80 font-medium cursor-default' 
                                : 'hover:bg-indigo-50 cursor-pointer group'
                            }`}
                          >
                            <td className="px-6 py-3 tabular-nums text-slate-700 group-hover:text-indigo-700">
                              {formatNumber(p.annualGenerationKwh)}
                              {isCurrent && <span className="ml-2 text-xs font-normal text-tines-purple bg-tines-purple/10 px-2 py-0.5 rounded-full">Current</span>}
                            </td>
                            <td className="px-6 py-3 text-right tabular-nums text-slate-600">{p.scaleFactor.toFixed(2)}×</td>
                            <td className="px-6 py-3 text-right tabular-nums text-slate-600">{formatNumber(p.exportKwh)} kWh</td>
                            <td className={`px-6 py-3 text-right tabular-nums font-medium ${isHighSpill ? 'text-amber-600' : 'text-slate-700'}`}>
                              {formatPercentFraction(p.spillageFraction)}
                              {isHighSpill && <span className="ml-2 text-xs font-normal text-amber-600">⚠️</span>}
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        )}

        {/* --- COMPARISON TAB --- */}
        {activeTab === 'comparison' && standardResult && marketResult && (
          <div className="animate-in fade-in duration-300">
            <div className="rounded-xl border border-slate-100 bg-white shadow-sm overflow-hidden mb-8">
              <div className="px-6 py-4 border-b border-slate-100 bg-slate-50/50">
                <h3 className="text-sm font-bold tracking-wider text-slate-500 uppercase">Scenario Comparison</h3>
                <p className="text-xs text-slate-400 mt-1">Standard Tariff vs Market Rate Analysis</p>
              </div>
              <div className="p-6">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  {/* Standard Result Card */}
                  <div className="bg-slate-50 rounded-lg p-5 border border-slate-200">
                    <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-4">Standard Tariff</h4>
                    <div className="space-y-3">
                      <div>
                        <div className="text-xs text-slate-500">Annual Savings</div>
                        <div className="text-lg font-bold text-emerald-600">{formatCurrency(standardResult.annualSavings)}</div>
                      </div>
                      <div>
                        <div className="text-xs text-slate-500">Payback Period</div>
                        <div className="text-lg font-bold text-slate-700">
                          {Number.isFinite(standardResult.simplePayback) ? `${standardResult.simplePayback.toFixed(1)} years` : '∞'}
                        </div>
                      </div>
                      <div>
                        <div className="text-xs text-slate-500">IRR (25y)</div>
                        <div className="text-lg font-bold text-slate-700">
                          {Number.isFinite(standardResult.irr) ? `${(standardResult.irr * 100).toFixed(1)}%` : '—'}
                        </div>
                      </div>
                      <div>
                        <div className="text-xs text-slate-500">NPV (25y)</div>
                        <div className="text-lg font-bold text-slate-700">{formatCurrency(standardResult.npv)}</div>
                      </div>
                      <div>
                        <div className="text-xs text-slate-500">Export Revenue</div>
                        <div className="text-sm font-semibold text-slate-600">{formatCurrency(standardResult.annualExportRevenue)}</div>
                      </div>
                    </div>
                  </div>

                  {/* Delta Card */}
                  <div className="bg-indigo-50 rounded-lg p-5 border border-indigo-200 flex flex-col justify-center">
                    <h4 className="text-xs font-bold text-indigo-700 uppercase tracking-wider mb-4 text-center">Market Rate Difference</h4>
                    <div className="space-y-3">
                      <div className="text-center">
                        <div className="text-xs text-indigo-600">Δ Annual Savings</div>
                        <div className="text-xl font-bold text-indigo-700">
                          {formatSignedCurrency(marketResult.annualSavings - standardResult.annualSavings)}
                        </div>
                      </div>
                      <div className="text-center">
                        <div className="text-xs text-indigo-600">Δ Payback</div>
                        <div className="text-xl font-bold text-indigo-700">
                          {(() => {
                            const delta = marketResult.simplePayback - standardResult.simplePayback;
                            if (!Number.isFinite(delta)) return '—';
                            const sign = delta >= 0 ? '+' : '−';
                            return `${sign}${Math.abs(delta).toFixed(1)}y`;
                          })()}
                        </div>
                      </div>
                      <div className="text-center">
                        <div className="text-xs text-indigo-600">Δ IRR</div>
                        <div className="text-xl font-bold text-indigo-700">
                          {(() => {
                            const delta = (marketResult.irr - standardResult.irr) * 100;
                            if (!Number.isFinite(delta)) return '—';
                            const sign = delta >= 0 ? '+' : '−';
                            return `${sign}${Math.abs(delta).toFixed(1)}%`;
                          })()}
                        </div>
                      </div>
                      <div className="text-center">
                        <div className="text-xs text-indigo-600">Δ NPV</div>
                        <div className="text-lg font-bold text-indigo-700">
                          {formatSignedCurrency(marketResult.npv - standardResult.npv)}
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Market Result Card */}
                  <div className="bg-slate-50 rounded-lg p-5 border border-slate-200">
                    <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-4">Market Rate</h4>
                    <div className="space-y-3">
                      <div>
                        <div className="text-xs text-slate-500">Annual Savings</div>
                        <div className="text-lg font-bold text-emerald-600">{formatCurrency(marketResult.annualSavings)}</div>
                      </div>
                      <div>
                        <div className="text-xs text-slate-500">Payback Period</div>
                        <div className="text-lg font-bold text-slate-700">
                          {Number.isFinite(marketResult.simplePayback) ? `${marketResult.simplePayback.toFixed(1)} years` : '∞'}
                        </div>
                      </div>
                      <div>
                        <div className="text-xs text-slate-500">IRR (25y)</div>
                        <div className="text-lg font-bold text-slate-700">
                          {Number.isFinite(marketResult.irr) ? `${(marketResult.irr * 100).toFixed(1)}%` : '—'}
                        </div>
                      </div>
                      <div>
                        <div className="text-xs text-slate-500">NPV (25y)</div>
                        <div className="text-lg font-bold text-slate-700">{formatCurrency(marketResult.npv)}</div>
                      </div>
                      <div>
                        <div className="text-xs text-slate-500">Export Revenue</div>
                        <div className="text-sm font-semibold text-slate-600">{formatCurrency(marketResult.annualExportRevenue)}</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* --- MARKET TAB --- */}
        {activeTab === 'market' && activeResult && activeResult.audit?.hourly && activeResult.audit.hourly.length > 0 && (
          <div className="mb-8 animate-in fade-in duration-300">
            <MarketAnalysis hourlyData={activeResult.audit.hourly} year={analyticsYear} />
          </div>
        )}

        {/* Footer Actions */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-slate-100">
          <div>
            {activeResult && activeResult.audit ? (
              <button
                type="button"
                className="text-sm font-medium text-slate-500 hover:text-tines-purple transition-colors"
                onClick={() => setAuditOpen(true)}
              >
                Open detailed auditor view
              </button>
            ) : (
              <span className="text-xs text-slate-400">Auditor view unavailable (no hourly data)</span>
            )}
          </div>

          <div className="flex gap-4">
            {onBack && (
              <button
                onClick={onBack}
                className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 shadow-sm hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
              >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18" />
                </svg>
                Edit Inputs
              </button>
            )}
            
            {onSaveReport && (
              <button
                onClick={() => setSaveModalOpen(true)}
                className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 shadow-sm hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
              >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z" />
                </svg>
                Save As...
              </button>
            )}

            <button className="inline-flex items-center gap-2 rounded-lg bg-tines-purple px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
              Download PDF Report
            </button>
          </div>
        </div>

        {auditOpen && activeResult && activeResult.audit && <AuditModal audit={activeResult.audit} onClose={() => setAuditOpen(false)} />}
        
        <SaveReportModal
          isOpen={saveModalOpen}
          existingNames={existingReportNames}
          onCancel={() => setSaveModalOpen(false)}
          onSave={(name) => {
            onSaveReport?.(name);
            setSaveModalOpen(false);
          }}
        />
      </div>
    </section>
  );
}
