/**
 * Metadata for the three Irish domestic house sample profiles.
 *
 * Each entry corresponds to a synthetic ESB HDF CSV file in
 * public/data/usages/, generated by scripts/generate_sample_house_profiles.py.
 *
 * All consumption figures are based on:
 *  - SEAI "Energy in Ireland 2024"
 *  - CSO Household Energy Survey 2020
 *  - SEAI BER Database stock averages
 *  - SEAI Heat Pump Monitoring Report 2023
 *  - Tipperary Energy Agency deep-retrofit monitoring data
 */

export interface SampleHouse {
  id: string;
  label: string;
  /** One-line description shown on the button. */
  tagline: string;
  /** Floor area in square metres (used for display only). */
  floorAreaM2: number;
  /** Approximate annual electricity consumption in kWh. */
  annualKwh: number;
  /** SEAI BER rating (display only). */
  berRating: string;
  /** URL path served from /public. */
  csvPath: string;
  /** Condensed source note shown below the selector. */
  sourceNote: string;
}

export const SAMPLE_HOUSES: SampleHouse[] = [
  {
    id: 'house-small-traditional',
    label: 'Small Traditional',
    tagline: '3-bed semi-d · ~80 m² · BER D · ~4,200 kWh/yr',
    floorAreaM2: 80,
    annualKwh: 4200,
    berRating: 'D',
    csvPath: '/data/usages/sample_house_small_traditional_2025.csv',
    sourceNote:
      'Pre-2000 gas-heated semi-detached. SEAI Energy in Ireland 2024; CSO Household Energy Survey.',
  },
  {
    id: 'house-large-traditional',
    label: 'Large Traditional',
    tagline: '4-bed detached · ~165 m² · BER D/E · ~6,800 kWh/yr',
    floorAreaM2: 165,
    annualKwh: 6820,
    berRating: 'D/E',
    csvPath: '/data/usages/sample_house_large_traditional_2025.csv',
    sourceNote:
      'Pre-1990 oil-heated detached. SEAI BER stock analysis 2022; SEAI Monitoring & Reporting Programme.',
  },
  {
    id: 'house-heat-pump',
    label: 'Heat Pump House',
    tagline: '4-bed semi-d · ~115 m² · BER B2 · ~9,350 kWh/yr',
    floorAreaM2: 115,
    annualKwh: 9320,
    berRating: 'B2',
    csvPath: '/data/usages/sample_house_heat_pump_2025.csv',
    sourceNote:
      'Well-retrofitted A2W heat pump, off-peak DHW boost. SEAI Heat Pump Monitoring 2023; Tipperary Energy Agency.',
  },
];
